# Generated by Django 5.1.2 on 2024-11-17 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_content_post_content_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='title',
            new_name='author',
        ),
    ]
